spring:
 security:
   user:
     name: testuser
     password: pass001
server:
  port: 8443
  ssl:
    key-store: classpath:localhost+2.p12  # 証明書ファイル
    key-store-type: PKCS12                # 証明書作成時のキーストアタイプ
    key-password: changeit                # mkcertデフォルト
    key-store-password: changeit          # mkcertデフォルト


